spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.222.225.41:1001/chat_db
    username: "{cipher}6fa9e998de565af3abbbc086608e7b087c2fd0ee7dda6495a03c7836d12c1204"
    password: "{cipher}31ad880c6bf423d0e0d0db401e442466824f06e380162970e50e11b94276c29f"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #         https
          issuer-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api
          jwk-set-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api/protocol/openid-connect/certs
#          local
#          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
#          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
openapi:
  service:
    title: chat-service
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /chat-service/v3/api-docs
  swagger-ui:
    path: /chat-service/swagger-ui.html