spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.222.225.41:1001/category_db
    username: "{cipher}6fa9e998de565af3abbbc086608e7b087c2fd0ee7dda6495a03c7836d12c1204"
    password: "{cipher}31ad880c6bf423d0e0d0db401e442466824f06e380162970e50e11b94276c29f"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: https://keycloak.trade-wise.online/auth
  credentials:
    username: 'tradewise'
    password: 'tradewise321'
    client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
    secret: '{cipher}42d5f710c20655adbeeb9e9eb6d161d048664f4a9e749ede11e2cefa937299e79dc63978e0e88f6eb32a730d84c50413514e4df55f056586a6813b2b647d445a'
    provider: secret
openapi:
  service:
    title: category-service
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /category-service/v3/api-docs
  swagger-ui:
    oauth:
      realm: 'go-selling-api'
      client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
      clientSecret: '{cipher}42d5f710c20655adbeeb9e9eb6d161d048664f4a9e749ede11e2cefa937299e79dc63978e0e88f6eb32a730d84c50413514e4df55f056586a6813b2b647d445a'
    path: /category-service/swagger-ui.html